# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      TEST_PROJECT: ${{ github.event.repository.name }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0
    - name: Restore dependencies
      run: dotnet restore "./${{ env.TEST_PROJECT }}/${{ env.TEST_PROJECT }}.csproj"
    - name: Build
      run: dotnet build "./${{ env.TEST_PROJECT }}/${{ env.TEST_PROJECT }}.csproj" --configuration Release --no-restore
    - name: Test
      run: dotnet test "./${{ env.TEST_PROJECT }}/${{ env.TEST_PROJECT }}.csproj" --no-restore --verbosity normal